---
- name: Configuring Systemd Service
  become: yes
  copy:
    src: '../ansible/config/worker-app.service'
    dest: '/etc/systemd/system/worker-app.service'
    owner: worker
    group: worker
    mode: 0644

- name: Creating service logging directory
  become: yes
  file:
    path: /var/opt/worker/logs
    state: directory
    owner: worker
    group: worker
    mode: 0775
