---
- hosts: all
  vars:
    some_var: 2
  remote_user: ubuntu
  tasks:
    - name: Test Connection with Ping.
      ping:
    - name: Perform apt update.
      become: yes
      apt:
        update_cache:
    - name: Installing Java8
      include_role:
        name: java8-jdk
    - name: Configure User
      include_role:
        name: worker-user
    - name: Configure Systemd Service
      include_role:
        name: configure-java-service
    - name: Deploy Worker App
      include_role:
        name: deploy-java-worker
