---
- hosts: all
  vars:
    some_var: 2
  remote_user: ubuntu
  tasks:
    - name: Test Connection with Ping.
      ping:
    - name: Perform apt update.
      become: yes
      apt:
        update_cache:
    - name: Installing Java8
      include_role:
        name: java8-oracle
